/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sfeir.kafka;
@org.apache.avro.specific.AvroGenerated
public enum Gender implements org.apache.avro.generic.GenericEnumSymbol<Gender> {
  MALE, FEMALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"com.sfeir.kafka\",\"symbols\":[\"MALE\",\"FEMALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
